# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zigzag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted_wish',
            field=models.BooleanField(default=False),
        ),
    ]
