# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zigzag_app', '0003_auto_20191021_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes_uploaded', to='zigzag_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='wish',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='wished_by',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
