# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zigzag_app', '0006_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
