# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zigzag_app', '0008_job_is_everyone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_everyone',
        ),
        migrations.AddField(
            model_name='job',
            name='picked_by',
            field=models.ManyToManyField(related_name='jobs_picked', to='zigzag_app.User'),
        ),
    ]
