# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zigzag_app', '0009_auto_20191022_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.BooleanField(default=True),
        ),
    ]
