# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 22:12
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zigzag_app', '0010_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Electrical', 'Electrical'), ('Garden', 'Garden'), ('Pet Care', 'Pet Care')], max_length=26),
        ),
    ]
