# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-22 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zigzag_app', '0011_auto_20191022_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.BooleanField(default=True),
        ),
    ]
